import { RECORD_SCHEMA } from "@/config/record-schema  ";

export const LABELS = RECORD_SCHEMA.labels;

export const FIELD_ALIASES = {
  hoTen: [
    "Họ tên",
    "Họ Tên",
    "Full Name",
    "Name",
    "Họ và tên",
    "Tên",
    "Tài xế",
    "NMH",
    "Người mang hàng",
  ],
  thuocCtyDonVi: ["Cty", "Công ty", "Company", "Công ty/Đơn vị", "Cty/Đơn vị"],
  liDoRaVaoCong: ["Lý do", "Mục đích", "Reason", "Purpose"],
  chiTietHangHoa: [
    "Chủng loại/Số lượng",
    "Chủng loại",
    "số lượng",
    "goods details",
    "Đặc tả hàng hóa",
    "Mô tả hàng hóa",
    "Hàng hóa",
    "hàng hóa",
    "Goods Description",
    "Chi Tiết Hàng hóa"
  ],
  soCont: ["Số Cont", "Số cont", "Số thùng cont", "cont no.", "Cont No."],
  soSeal: ["Số Seal", "Số seal", "Seal", "seal"],
  gioVao: ["Giờ vào", "Thời gian vào", "Time in", "Vào", "Vào cổng lúc"],
  gioRa: [
    "Giờ ra",
    "Thời gian ra",
    "Time out",
    "Ra",
    "Ra cổng lúc",
    "rời",
    "Rời",
  ],
  nguoiLienHe: [
    "Người liên hệ",
    "Contact Person",
    "liên hệ",
    "Người nhận hàng",
  ],
  soPhieu: ["BPMs", "Phiếu MHRC", "BPM"],
  loaiPhuongTien: ["Phương tiện", "Loại xe"],
  bks: [
    "BSX",
    "bsx",
    "Bsx",
    "BKS",
    "Bks",
    "bks",
    "Plate No.",
    "Biển số xe",
    "Biển Số Xe",
  ],
  bksRomooc: ["Rơ-mooc", "Rơ móc", "Rơ-móc", "ro mooc", "rơ-mooc", "Rơ Mooc"],
  id: [
    "cccd",
    "CCCD/GPLX",
    "Cccd",
    "GPLX",
    "BST",
    "Số thẻ",
    "MST",
    "VAT",
    "Employee ID",
  ],
  xuongGiao: [
    "cty",
    "Cty/Đơn vị",
    "Công ty",
    "Giao",
    "Xưởng Xuất",
    "Xưởng nhập",
    "xưởng nhập",
    "xưởng Nhập",
    "Delivery",
    "Export Factory",
  ],
  xuongNhan: [
    "cty",
    "Cty/Đơn vị",
    "Công ty",
    "Nhận",
    "Xưởng Nhập",
    "Received",
    "Import Factory",
  ],
};
