services:
  - type: web
    name: quick-report-api
    runtime: node
    plan: free
    buildCommand: npm install && cd clients && npm install && npm run build && cd ..
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /opt/render/project/src/storage/data/quick-report.db
      - key: TEMPLATE_DIR
        value: /opt/render/project/src/templates
      - key: EXPORT_DIR
        value: /opt/render/project/src/storage/reports
    disk:
      name: quick-report-data
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
